---
title: "Blog Post #1 - Not All Data is Good Data"
---

### How Statistics and Data Analysis Have Been Used to Further Oppress, Silence, and Harm Minority Groups

  
  The history of science and mathematics is one that is complex. Historically, women were seen as beneath men intellectually, causing them to be left out of the conversation. The field of science and technology has long been dominated by men, and not until more recent times have women started being considered essential to the discussion. While there have been strides for equality within the field, there is still a lot of work that needs to be done. 
  
  People like to assume that data is honest, clean, and unbiased. However, that is not the case. Data can be manipulated and used to manipulate. One of the most famous books regarding how to manipulate statistics is [*How To Lie With Statistics*](https://www.researchgate.net/profile/Grigori-Evreinov/post/Data-visualization-which-is-best-for-within-and-cross-source-data/attachment/5b0690b6b53d2f63c3cdcad5/AS%3A629755908993031%401527156917765/download/How-to-Lie-with-Statistics.pdf) by Darrell Huff. The book explains the multitude of ways that data can be manipulated and presented in a misleading way. I say misleading instead of dishonest because the numbers may be accurate through statistical analysis, but the reason and way they are presented could be misleading. The topic of biased data is also discussed in [*Algorithms of Oppression*](https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5wb2R0cmFjLmNvbS8xOVd6VlR4MV9IZlg/episode/dGFnOnNvdW5kY2xvdWQsMjAxMDp0cmFja3MvNzA5MjIwMjQ1?hl=en&ved=2ahUKEwi09prJoPzuAhUCh-AKHdz_AZsQjrkEegQICRAI&ep=6) by Safiya Umoja Noble. She explains how the code behind search engines discriminate against oppressed groups. One example she provides is a simple Google search about Black women which led to explicit photos and videos within the first few pages of the search. When white men are Googled there are no explicit videos or photos among the top recommended results. 
  
  Smith College should make ethics a core part of its curriculum, especially among the STEM majors. This would help ensure that all Smith students understand the history (both good and bad) and ethical concerns of one’s field so that we can enter the workplace with the skills to acknowledge and fight against oppression. 
 

A digital copy of *Data Feminism* can be found [here.](https://mitpressonpubpub.mitpress.mit.edu/pub/dgv16l22/release/6)
